In [ ]:
 import pandas as pd
 import numpy as np

In [ ]:
df=pd.read_csv('sales_data_3.csv')
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23.0,45.0,120.0,1366.0,1035.0,2401.0
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20.0,45.0,120.0,1188.0,900.0,2088.0
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4.0,45.0,120.0,238.0,180.0,418.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31782,2014-06-26,26,June,2014,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",16.0,13.0,35.0,279.0,208.0,487.0
31783,2016-06-26,26,June,2016,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",17.0,13.0,35.0,297.0,221.0,518.0
31784,2014-01-27,27,January,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",9.0,13.0,35.0,141.0,117.0,258.0
31785,2014-01-27,27,January,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",1.0,13.0,35.0,16.0,13.0,29.0
31786,2016-01-27,27,January,2016,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# What is the average age of the customers?

In [ ]:
avg_age=df['Customer_Age'].mean()
avg_age

36.11724918992041

In [ ]:
# How do different age groups behave in terms of purchases?

In [ ]:
behave=df.groupby('Age_Group')['Revenue'].sum()
behave

Age_Group
Adults (35-64)          3181649.0
Seniors (64+)             41447.0
Young Adults (25-34)    1993050.0
Youth (<25)              853859.0
Name: Revenue, dtype: float64

In [ ]:
 # What are the purchasing patterns across different genders

In [ ]:
pur_pattern=df.groupby('Customer_Gender')['Revenue'].sum()
pur_pattern

Customer_Gender
F    2866922.0
M    3203083.0
Name: Revenue, dtype: float64

In [ ]:
# Which countries/states have the highest/lowest sales revenue

In [ ]:
sale_revenue_c=df.groupby('Country')['Revenue'].sum()
high=sale_revenue_c.idxmax()
low=sale_revenue_c.idxmin()
print(high)
print(low)

United States
France

In [ ]:
sale_revenue_s=df.groupby('State')['Revenue'].sum()
high_s=sale_revenue_s.idxmax()
low_s=sale_revenue_s.idxmin()
print(high_s)
print(low_s)

California
Virginia

In [ ]:
# Are there geographical trends in product preference?

In [ ]:
# Do customers from certain countries/states tend to buy certain        products?

In [ ]:
coun_tend=df.groupby(['Country','Product'])['Revenue'].sum()
coun_tend

Country        Product
Australia      AWC Logo Cap               100873.0
               All-Purpose Bike Stand      93945.0
               Bike Wash - Dissolver       45999.0
               Fender Set - Mountain      178330.0
               Half-Finger Gloves, L       55571.0
                                            ...
United States  Road Bottle Cage            89721.0
               Sport-100 Helmet, Black     98022.0
               Sport-100 Helmet, Blue      70744.0
               Sport-100 Helmet, Red       91738.0
               Water Bottle - 30 oz.      278789.0
Name: Revenue, Length: 84, dtype: float64

In [ ]:
# Which products/sub-categories have the highest sales/revenue?

In [ ]:
p_max=df.groupby('Product')['Revenue'].sum().idxmax()
sp=df.groupby('Sub_Category')['Revenue'].sum().idxmax()
print(p_max)
print(sp)

Fender Set - Mountain
Bottles and Cages

In [ ]:
# What is the profitability of different products/categories?

In [ ]:
profitability=df.groupby(['Product'])['Profit'].sum()
profitability

Product
AWC Logo Cap                78008.0
All-Purpose Bike Stand     201064.0
Bike Wash - Dissolver      116008.0
Fender Set - Mountain      749041.0
Half-Finger Gloves, L      166721.0
Half-Finger Gloves, M      152834.0
Half-Finger Gloves, S      191760.0
Hitch Rack - 4-Bike        305326.0
Mountain Bottle Cage       189009.0
Road Bottle Cage           203754.0
Sport-100 Helmet, Black    190045.0
Sport-100 Helmet, Blue     167957.0
Sport-100 Helmet, Red      190780.0
Water Bottle - 30 oz.      417843.0
Name: Profit, dtype: float64

In [ ]:
# Which products have the highest order quantities?

In [ ]:
high_order=df.groupby('Product')['Order_Quantity'].sum().idxmax()
high_order

'Water Bottle - 30 oz.'

In [ ]:
# Which products generate the highest profit margins?

In [ ]:
df['Profit_margin'] = df['Profit'] / df['Revenue']
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,profit_margin,Profit_margin
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0,0.621053,0.621053
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0,0.621053,0.621053
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23.0,45.0,120.0,1366.0,1035.0,2401.0,0.568930,0.568930
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20.0,45.0,120.0,1188.0,900.0,2088.0,0.568966,0.568966
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4.0,45.0,120.0,238.0,180.0,418.0,0.569378,0.569378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31782,2014-06-26,26,June,2014,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",16.0,13.0,35.0,279.0,208.0,487.0,0.572895,0.572895
31783,2016-06-26,26,June,2016,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",17.0,13.0,35.0,297.0,221.0,518.0,0.573359,0.573359
31784,2014-01-27,27,January,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",9.0,13.0,35.0,141.0,117.0,258.0,0.546512,0.546512
31785,2014-01-27,27,January,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",1.0,13.0,35.0,16.0,13.0,29.0,0.551724,0.551724
31786,2016-01-27,27,January,2016,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
high_profit_margins=df.groupby('Product')['Profit_margin'].sum().idxmax()
high_profit_margins

'Water Bottle - 30 oz.'

In [ ]:
# How does the unit cost compare to the unit price across different products?

In [ ]:
# Are the seasonal trends in product purchases based on the date/month/year?

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31787 entries, 0 to 31786
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              31787 non-null  object
 1   Day               31787 non-null  int64
 2   Month             31787 non-null  object
 3   Year              31787 non-null  int64
 4   Customer_Age      31787 non-null  int64
 5   Age_Group         31786 non-null  object
 6   Customer_Gender   31786 non-null  object
 7   Country           31786 non-null  object
 8   State             31786 non-null  object
 9   Product_Category  31786 non-null  object
 10  Sub_Category      31786 non-null  object
 11  Product           31786 non-null  object
 12  Order_Quantity    31786 non-null  float64
 13  Unit_Cost         31786 non-null  float64
 14  Unit_Price        31786 non-null  float64
 15  Profit            31786 non-null  float64
 16  Cost              31786 non-null  float64
 17  Revenue           31786 non-null  float64
 18  profit_margin     31786 non-null  float64
 19  Profit_margin     31786 non-null  float64
dtypes: float64(8), int64(3), object(9)
memory usage: 4.9+ MB

In [ ]:
df['Date']=pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31787 entries, 0 to 31786
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              31787 non-null  datetime64[ns]
 1   Day               31787 non-null  int64
 2   Month             31787 non-null  object
 3   Year              31787 non-null  int64
 4   Customer_Age      31787 non-null  int64
 5   Age_Group         31786 non-null  object
 6   Customer_Gender   31786 non-null  object
 7   Country           31786 non-null  object
 8   State             31786 non-null  object
 9   Product_Category  31786 non-null  object
 10  Sub_Category      31786 non-null  object
 11  Product           31786 non-null  object
 12  Order_Quantity    31786 non-null  float64
 13  Unit_Cost         31786 non-null  float64
 14  Unit_Price        31786 non-null  float64
 15  Profit            31786 non-null  float64
 16  Cost              31786 non-null  float64
 17  Revenue           31786 non-null  float64
 18  profit_margin     31786 non-null  float64
 19  Profit_margin     31786 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(3), object(8)
memory usage: 4.9+ MB

In [ ]:
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue,profit_margin,Profit_margin
0,2013-11-26,26,11,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0,0.621053,0.621053
1,2015-11-26,26,11,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8.0,45.0,120.0,590.0,360.0,950.0,0.621053,0.621053
2,2014-03-23,23,3,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23.0,45.0,120.0,1366.0,1035.0,2401.0,0.568930,0.568930
3,2016-03-23,23,3,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20.0,45.0,120.0,1188.0,900.0,2088.0,0.568966,0.568966
4,2014-05-15,15,5,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4.0,45.0,120.0,238.0,180.0,418.0,0.569378,0.569378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31782,2014-06-26,26,6,2014,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",16.0,13.0,35.0,279.0,208.0,487.0,0.572895,0.572895
31783,2016-06-26,26,6,2016,39,Adults (35-64),M,Germany,Nordrhein-Westfalen,Accessories,Helmets,"Sport-100 Helmet, Blue",17.0,13.0,35.0,297.0,221.0,518.0,0.573359,0.573359
31784,2014-01-27,27,1,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",9.0,13.0,35.0,141.0,117.0,258.0,0.546512,0.546512
31785,2014-01-27,27,1,2014,45,Adults (35-64),F,France,Seine (Paris),Accessories,Helmets,"Sport-100 Helmet, Black",1.0,13.0,35.0,16.0,13.0,29.0,0.551724,0.551724
31786,2016-01-27,27,1,2016,45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# What is the distribution of order quantities across different products?

In [ ]:
order_quantity_distribution = df.groupby('Product')['Order_Quantity'].sum().describe()
print(order_quantity_distribution)

count        14.000000
mean      33963.214286
std       42789.499395
min        2400.000000
25%       10249.250000
50%       13973.500000
75%       39493.000000
max      164086.000000
Name: Order_Quantity, dtype: float64

In [ ]:
# Which products are often purchased in bulk?

In [ ]:
bulk_purchases = df[df['Order_Quantity'] > 10].groupby('Product')['Order_Quantity'].sum().idxmax()
print(bulk_purchases)

Water Bottle - 30 oz.

In [ ]:
# What is the total revenue and profit generated by each product/category?

In [ ]:
revenue_profit_by_category = df.groupby(['Product_Category', 'Product'])[['Revenue', 'Profit']].sum()
print(revenue_profit_by_category)

                                            Revenue    Profit
Product_Category Product
Accessories      AWC Logo Cap                 459.0      95.0
                 All-Purpose Bike Stand    342664.0  201064.0
                 Bike Wash - Dissolver     198745.0  116008.0
                 Fender Set - Mountain    1245350.0  748702.0
                 Hitch Rack - 4-Bike       519211.0  305326.0
                 Mountain Bottle Cage      338929.0  189009.0
                 Road Bottle Cage          324246.0  203754.0
                 Sport-100 Helmet, Black   322034.0  190045.0
                 Sport-100 Helmet, Blue    284398.0  167957.0
                 Sport-100 Helmet, Red     327774.0  190780.0
                 Water Bottle - 30 oz.     745999.0  417835.0
Clothing         AWC Logo Cap              548761.0   77913.0
                 Fender Set - Mountain        635.0     339.0
                 Half-Finger Gloves, L     285098.0  166721.0
                 Half-Finger Gloves, M     260780.0  152834.0
                 Half-Finger Gloves, S     324906.0  191760.0
                 Water Bottle - 30 oz.         16.0       8.0